CREATE TABLE SERIE_ANCS(
CodSerie NUMBER(2) PRIMARY KEY,
DenSerie VARCHAR2(12) NOT NULL,
NrGrupe NUMBER(2) DEFAULT 0,
An NUMBER(1) DEFAULT 1 );

CREATE TABLE GRUPA_ANCS(
CodGrupa NUMBER(2) PRIMARY KEY,
DenGrupa VARCHAR2(12) NOT NULL,
NrStudenti NUMBER(3) DEFAULT 0,
CodSerie NUMBER(2) REFERENCES SERIE_ANCS(CodSerie) );
